title: My blog
author: Minku Singh
email: singhminku443@gmail.com
description: > # this means to ignore newlines until "baseurl:"
So lets talk about the experience I've got while learning coding.  
# social links
twitter_username: minkusingh_ # DO NOT include the @ character, or else the build will fail!
github_username:  minkusingh443 # DO NOT include the @ character, or else the build will fail!
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
